### PR TITLE
Add basic unit test infrastructure

### PR DESCRIPTION
**Pull request by waf**
basic karma/jasmine unit test set up

includes a single, sample unit test in `test/github-serialization.test.js`

### CODE REVIEW

**Comment by waf** [comment]
@pangaunn I'd appreciate your review on this, if you have time. It's my first time setting up karma / webpack / vuejs unit testing. Thanks!

**Comment by ches** [comment]
Ran `npm test` on your branch and it works for me! Didn't know about headless Chrome that works without Xvfb as an alternative to PhantomJS. Good stuff.

One thought: if we want to [do builds on Travis][1], by default it uses `npm test` for Node builds, but that will need to use `--single-run` on the `karma` command so it exits (to my confusion, the options have to come after the config file in the command). We can either customize the command Travis runs or make a different script task for testing in watch mode.

[Mocha] plus Chai for `expect` (and other) assertions seems like a popular modern alternative to Jasmine, nice reporters and the diffs feature looks good (though I haven't tried whether these are shown when run through Karma)—I'm not much of a JS guy at all, just taking this as an opportunity to brush up; @pangaunn what are you accustomed to using?

[1]: http://karma-runner.github.io/1.0/plus/travis.html
[Mocha]: http://mochajs.org/

**Comment by ches** [comment]
Ah, looks like diff reports can be had with [this](https://www.npmjs.com/package/karma-mocha-reporter#showdiff), if karma-mocha is used as well.

**Comment by pangaunn** [comment]
@ches I'm using jest. it is super easy to mock function. It also has snapshot testing.
@waf I never setting up karma before. But it look good for me.

**Review by pangaunn — APPROVED** [review]

**Comment by waf** [comment]
great, thanks for all the input @ches and @pangaunn. I'll look into mocha/chai/jest. Now that we have a basic karma infrastructure working, it shouldn't be too hard to play around with various library combinations. I'll also see if I can get code coverage (via istanbul?) up and running.

Good point about the travis configuration. I'll probably keep `npm test` as it's nice and easy to type for developers, and configure travis to run something else. Open for discussion, of course.

**Comment by waf** [comment]
After playing around with some of the various testing libraries out there, I ended up really liking Jest. Thanks for the recommendation, @pangaunn! It seems to require very little configuration and just works. It has built-in code coverage and the snapshot testing looks pretty interesting, too.

I've added a `.travis.yml` file, but it looks like I don't have enough permission to enable Travis CI for this repo:

screen shot 2017-10-04 at 8 49 51 pm

@ches, would you be able to enable Travis CI for our hackmap repo, here? https://travis-ci.org/profile/bkkhack Thanks!

**Comment by djay** [comment]
Done.

FYI I use robotframework and circleci now for my functional tests. I like the BDD style tests.

For example here is one test from my suite

Scenario: I can rename a form and then create new form and then go back and repeat
  Given I have a form open
   When I enter "new-form" in "Id" in "Form Settings"
    and I can see "new-form" is open
    and I enter "new-form-1" in "Id" in "Form Settings"
    and I can see "new-form-1" is open
    and I add a form by click
    and I can see "new-form" is open
    and I open a form "new-form-1"
    and I enter "new-form" in "Id" in "Form Settings"
    and I add a form by click
   Then I can see “new-form-1" is open

**Comment by waf** [comment]
Thanks @djay! robotframework looks interesting. I'll play around with it!

**Comment by waf** [comment]
Travis CI passes! I'll merge this PR, and add unit tests over time.

**Comment by djay** [comment]
FYI my setup is using docker in docker to build the app and use compose with selenium hub docker images to run my tests. This means its easy to run the tests on multiple browsers. I think you can also achieve the same thing for free using saucelabs for open source projects though.

**Pull request merged**
