### PR TITLE
Add ability to see history hackmap

### PR DESCRIPTION
**Pull request by pangaunn**
#7 
For most recently hack it will point to https://bkkhack.github.io/hackmap/ .
If you want to see a hack history you have to navigate to https://bkkhack.github.io/hackmap/:IssueNumber ie https://bkkhack.github.io/hackmap/2

### CODE REVIEW

**Comment by waf** [comment]
This is a great feature! I know @djay will be excited about it.  It will take me a bit of time to understand the router usage, but I'll get this merged as soon as I can. Thanks!

**Comment by waf** [comment]
Thanks!

**Comment by djay** [comment]
great. Would it also be possible for https://bkkhack.github.io/hackmap/ to redirect to the current map url that includes the ticket number? That will mean any urls passed around will continue to work when the links to hacks are implemented.

**Comment by ches** [comment]
This doesn't seem to be working now, like <https://bkkhack.github.io/hackmap/43> should get us to the February hack night if I'm not mistaken—did we have a regression since this PR, or is there maybe some issue with vue-router when served from GH Pages?

**Comment by pangaunn** [comment]
@ches I already tested on gh pages on my repository. I will check it again.

**Comment by waf** [comment]
We might have to switch from HTML5 history mode to hash-based history mode. If we have a url like this:

https://bkkhack.github.io/hackmap/43

The initial request will be a 404. We don't see that during development because the webpack dev server does some weird stuff where it redirects back to the application root.

**Pull request merged**
